name: S3 Host

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Copy to bucket
      run: |
        aws s3 sync . s3://airplan.alexjbuck.com --delete --exclude '.vscode/*' --exclude '.github/*' --exclude '.git/*' --exclude 'terraform/*'
